### ISSUE TITLE
Should CanopyAssim equal the daily biomass increment? 

### ISSUE THREAD

**Issue by dlebauer** [ebimodeling/biocro#17]
What accounts for the differences? I've tried searching throught the code, but can't figure out where CanopyAssim is calculated. The documentation defines CanopyAssim as "Hourly canopy assimilation, (Mg ha^-1 ground hr^-1).", but it isn't clear if this should be NPP or GPP, though GPP should always be >0 which isn't the case.

```
library(BioCro)
data(weather05)
x <- BioGro(weather05)
Biomass <- x$Leaf+x$Stem+x$Root+x$Grain+x$Rhizome
NPP <- c(0, diff(Biomass))

plot(x$CanopyAssim[1000:1100], type = 'l')
lines(NPP[1000:1100], col = 'red')
```
CanopyAssim (black) and Biomass Increment (red) for 100 hourly time steps:

![image](https://user-images.githubusercontent.com/464871/148615046-828c156a-6e90-442d-b8f0-cbaf92f9c5e0.png)

**Comment by justinmcgrath** [comment]
I recall that this happens due to a respiration calculation outside of the canopy assimilation equations - here maybe: https://github.com/ebimodeling/biocro/blob/26e0125b6f144e7cec9cc6fad10d85fda4375466/src/BioCro.c#L394.

It doesn't seem like good C accounting. In the new framework, there's a module that doesn't have that calculation, but I don't remember if it fixed the entire problem.

FYI, the paper has been accepted and we're in the process of moving everything to this repository. We'll update master, which will break anything pointing directly to it, so people may want to point things to specific commits to keep things from breaking. We'll only use this for development from then on.

**Comment by dlebauer** [comment]
Thank you!
