### ISSUE TITLE
Transpiration 

### ISSUE THREAD

**Issue by pnlfang** [ebimodeling/biocro#2]
I started with c3Can using doy124 and printed out the transpiration.  Priestly option seems to be reasonable, but Penman seems to be different from the plot in the manual.  Could there be an issue?  Thanks!
Yilin

**Comment by justinmcgrath** [comment]
Can you provide the version you are using, the code you used to produce the data, and the specific page in the manual you're referring to?

**Comment by pnlfang** [comment]
Sorry for the delay.  I don't check this inbox often.  For future
correspondence, please send to yilin.fang@pnnl.gov (cc'd as well).
The version I used is in the github master version.  Attached is the code I
used to produce the data.  The page I referred to is p22 in the attached
manual.

Thanks,
Yilin

**Comment by justinmcgrath** [comment]
Hi Yilin,
This is a comment thread on GitHub, so attachments are not posted to the thread if you reply by email Could you send the code in the body of the message or use the Web page to attach the file?

**Comment by pnlfang** [comment]
Hi,
The manual is biocro-manual-knitr.pdf under biocro/vignettes/
The following is the code:

dyn.load("../src/biocroLib.so",local=TRUE)

source("../R/c3CanA.R")
source("../R/BioCro.R")
load("../data/doy124.rda")
doy124
 tmp1 <- numeric(24)
 tmp2 <- numeric(24)

 for(i in 1:24){
    lai <- doy124[i,1]
    doy <- doy124[i,3]
    hr  <- doy124[i,4]
  solar <- doy124[i,5]
   temp <- doy124[i,6]
     rh <- doy124[i,7]
     ws <- doy124[i,8]

   tmp1[i] <-
c3CanA(lai,doy,hr,solar,temp,rh,ws,nlayers=1,heightFactor=40,c3photoControl=ll.0,lnControl=ln)$TranEpries
   tmp2[i] <-
c3CanA(lai,doy,hr,solar,temp,rh,ws,lat=45,nlayers=1,heightFactor=40,c3photoControl=ll.0,lnControl=ln)$TranEpen

 }

Thanks,
Yilin

**Comment by justinmcgrath** [comment]
Thanks for spotting this. It appears to be a problem with the doy124 data set, in which the relative humidity is out of phase with what is normal; the maximum is in the middle of the day instead of during the night.

doy124 was likely interpolated from lower resolution data, and relative humidity wasn't treated properly. It is something that should be fixed, but in the meantime, the only solution is to use one of the other transpiration estimates or use a better source of weather data.
