### ISSUE TITLE
Is it OK to put the last release of biocro-dev here?

### ISSUE THREAD

**Issue by justinmcgrath** [ebimodeling/biocro#5]
@dlebauer, before I started reworking the BioCro framework, I cleaned up a lot of the code to remove compiler warnings and make things easier to follow. Can that release be published here? I don't know if any aspects are unpublished from that release.

If it's OK to publish it here then how would I accomplish that. biocro and biocro-dev don't seem to have a common history, so I don't know how to incorporate those changes other than overwriting the files and committing them.

**Comment by dlebauer** [comment]
@justinmcgrath please do. the repositories do have a common history at least through v0.93 almost all of what I did since then was update the README and add dan's Willow paper (see the list of changes here: https://github.com/ebimodeling/biocro/commits/master anything since March 5 2015 is probably different from biocro-dev. ). You should be able to 

```sh
git clone git@github.com:ebimodeling/biocro # if you haven't already

git remote add biocro-dev git@github.com:ebimodeling/biocro-dev
git fetch biocro-dev
git checkout -b biocro-dev biocro-dev/master 12345 # replace 12345 with tag or git commit sha
git checkout master
git merge biocro-dev
```

from https://stackoverflow.com/a/1768800/199217

**Comment by justinmcgrath** [comment]
Thanks. HEAD should now have 0.95 from biocro-dev and the changes you made in biocro.
